/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantilla;

import javax.swing.JOptionPane;

/**
 *
 * @author andres
 */
public class Eighth extends javax.swing.JFrame {

    /**
     * Creates new form eighth
     */
    public Eighth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IncodeExpenses = new javax.swing.JPanel();
        IncodeMonth = new javax.swing.JLabel();
        MoMoney = new javax.swing.JLabel();
        EarningMoney = new javax.swing.JLabel();
        Save = new javax.swing.JButton();
        IncodeMoney = new javax.swing.JTextField();
        MoOutflows = new javax.swing.JTextField();
        EaningMonth = new javax.swing.JTextField();
        Behind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IncodeExpenses.setBorder(javax.swing.BorderFactory.createTitledBorder("Incode and expenses of the month"));

        IncodeMonth.setText("Incode money month:");

        MoMoney.setText("Mo money outflows:");

        EarningMoney.setText("Earning money in the month");

        Save.setText("save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Behind.setText("Behind");
        Behind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BehindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IncodeExpensesLayout = new javax.swing.GroupLayout(IncodeExpenses);
        IncodeExpenses.setLayout(IncodeExpensesLayout);
        IncodeExpensesLayout.setHorizontalGroup(
            IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncodeExpensesLayout.createSequentialGroup()
                .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IncodeExpensesLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(EarningMoney)
                            .addComponent(MoMoney)
                            .addComponent(IncodeMonth))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(IncodeMoney, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(MoOutflows)
                            .addComponent(EaningMonth)))
                    .addGroup(IncodeExpensesLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(Save)
                        .addGap(52, 52, 52)
                        .addComponent(Behind)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        IncodeExpensesLayout.setVerticalGroup(
            IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IncodeExpensesLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IncodeMonth)
                    .addComponent(IncodeMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MoMoney)
                    .addComponent(MoOutflows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EarningMoney)
                    .addComponent(EaningMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(IncodeExpensesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Save)
                    .addComponent(Behind))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IncodeExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IncodeExpenses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BehindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BehindActionPerformed
        // TODO add your handling code here:
        Third obj= new  Third();
            obj.setVisible(true);
            this.dispose();
    }//GEN-LAST:event_BehindActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        // TODO add your handling code here:
        if (Save.getText().equalsIgnoreCase("New")){
         saveInterfaz();
       }
       else
           saveInterfaz(); 
             
                      
    }//GEN-LAST:event_SaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eighth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eighth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eighth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eighth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eighth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Behind;
    private javax.swing.JTextField EaningMonth;
    private javax.swing.JLabel EarningMoney;
    private javax.swing.JPanel IncodeExpenses;
    private javax.swing.JTextField IncodeMoney;
    private javax.swing.JLabel IncodeMonth;
    private javax.swing.JLabel MoMoney;
    private javax.swing.JTextField MoOutflows;
    private javax.swing.JButton Save;
    // End of variables declaration//GEN-END:variables

    private void saveInterfaz() {
         if(IncodeMoney.getText().equals("")
               ||MoOutflows.getText().equals("") 
               || EaningMonth.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Plaese fill the requiered fields","Error",JOptionPane.ERROR_MESSAGE);
       }
    }
}
