/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package plantilla;

import java.awt.Event;
import java.util.List;
import javax.swing.JOptionPane;
import Event.persistence.FlatFile;

/**
 *
 * @author andres
 */

public class Fifth extends javax.swing.JFrame {
     private List<Event> eventList;
    private int indexEvent;

    public List<Event> getEventList() {
        return eventList;
    }

    public void setEventList(List<Event> eventList) {
        this.eventList = eventList;
    }

    public int getIndexEvent() {
        return indexEvent;
    }

    public void setIndexEvent(int indexEvent) {
        this.indexEvent = indexEvent;
    }
    final String filename="event.csv";
    final String separator = ",";

   
    /**
     * Creates new form Fifth
     */
    public Fifth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        event = new javax.swing.JPanel();
        EventIn = new javax.swing.JLabel();
        CustomerNa = new javax.swing.JLabel();
        CustomerDo = new javax.swing.JLabel();
        Food = new javax.swing.JLabel();
        Decoration = new javax.swing.JLabel();
        Derscription = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Document = new javax.swing.JTextField();
        FoodEv = new javax.swing.JTextField();
        DecorationEv = new javax.swing.JTextField();
        Description = new javax.swing.JTextField();
        Behind = new javax.swing.JButton();
        Save = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        event.setBorder(javax.swing.BorderFactory.createTitledBorder("Event"));

        EventIn.setText("Event info");

        CustomerNa.setText("Customer name for the event:");

        CustomerDo.setText("Customer document for the event:");

        Food.setText("Food for the event:");

        Decoration.setText("Decoration for the event:");

        Derscription.setText("Derscription for the event:");

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });

        Document.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentActionPerformed(evt);
            }
        });

        Behind.setText("Behind");
        Behind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BehindActionPerformed(evt);
            }
        });

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout eventLayout = new javax.swing.GroupLayout(event);
        event.setLayout(eventLayout);
        eventLayout.setHorizontalGroup(
            eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventLayout.createSequentialGroup()
                .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Derscription)
                            .addComponent(CustomerNa)
                            .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(EventIn)
                                .addComponent(CustomerDo))
                            .addComponent(Food)
                            .addComponent(Decoration)))
                    .addGroup(eventLayout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(Behind)))
                .addGap(18, 18, 18)
                .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Save)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DecorationEv, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FoodEv, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        eventLayout.setVerticalGroup(
            eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eventLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(EventIn)
                .addGap(22, 22, 22)
                .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerNa)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomerDo)
                    .addComponent(Document, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(eventLayout.createSequentialGroup()
                        .addComponent(Food)
                        .addGap(18, 18, 18)
                        .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Decoration)
                            .addComponent(DecorationEv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Derscription)
                            .addComponent(Description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(FoodEv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(eventLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Behind)
                    .addComponent(Save)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(event, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
if (Save.getText().equalsIgnoreCase("New")){
         saveInterfaz();
       }
       else
           saveInterfaz(); 
             
    }//GEN-LAST:event_SaveActionPerformed

    private void BehindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BehindActionPerformed
        // TODO add your handling code here:
           Second obj = new Second();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BehindActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fifth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fifth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Behind;
    private javax.swing.JLabel CustomerDo;
    private javax.swing.JLabel CustomerNa;
    private javax.swing.JLabel Decoration;
    private javax.swing.JTextField DecorationEv;
    private javax.swing.JLabel Derscription;
    private javax.swing.JTextField Description;
    private javax.swing.JTextField Document;
    private javax.swing.JLabel EventIn;
    private javax.swing.JLabel Food;
    private javax.swing.JTextField FoodEv;
    private javax.swing.JTextField Name;
    private javax.swing.JButton Save;
    private javax.swing.JPanel event;
    // End of variables declaration//GEN-END:variables

    private void saveInterfaz() {
         if(Name.getText().equals("")
               ||Document.getText().equals("") 
               || FoodEv.getText().equals("")
               || DecorationEv.getText().equals("")
               ||Description.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Plaese fill the requiered fields","Error",JOptionPane.ERROR_MESSAGE);
       }
    }
}